//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryCanvas.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoryCanvas.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutApplication {
            get {
                return ResourceManager.GetString("AboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Storyline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewStoryline {
            get {
                return ResourceManager.GetString("AddNewStoryline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Age に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (c) KMY 2016-2017 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationCopyright {
            get {
                return ResourceManager.GetString("ApplicationCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using Libraries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationLibrary {
            get {
                return ResourceManager.GetString("ApplicationLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StoryCanvas に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2.2.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply parameter to existing people に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyParameterForExistingPeople {
            get {
                return ResourceManager.GetString("ApplyParameterForExistingPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Save (1 minute) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSave {
            get {
                return ResourceManager.GetString("AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto save is disabled because no slot selected to save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSaveDisabledBecauseNoSlotSelected {
            get {
                return ResourceManager.GetString("AutoSaveDisabledBecauseNoSlotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto save is disabled because of story setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSaveDisabledBecauseOfStoryConfig {
            get {
                return ResourceManager.GetString("AutoSaveDisabledBecauseOfStoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto save is disabled because waiting for user action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSaveDisabledBecauseWaitingUserAction {
            get {
                return ResourceManager.GetString("AutoSaveDisabledBecauseWaitingUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto save is enabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSaveEnabled {
            get {
                return ResourceManager.GetString("AutoSaveEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After creating new story, auto save is disabled until you save to a slot manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSaveNotice {
            get {
                return ResourceManager.GetString("AutoSaveNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Being called に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BeingCalledName {
            get {
                return ResourceManager.GetString("BeingCalledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birthday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CallingName {
            get {
                return ResourceManager.GetString("CallingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chapter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chapter and Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChapterText {
            get {
                return ResourceManager.GetString("ChapterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChooseNetwork {
            get {
                return ResourceManager.GetString("ChooseNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cloud に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New Story に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateNewStory {
            get {
                return ResourceManager.GetString("CreateNewStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Death day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeathDay {
            get {
                return ResourceManager.GetString("DeathDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you delete this entity? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteEntityMessage {
            get {
                return ResourceManager.GetString("DeleteEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty Slot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmptySlot {
            get {
                return ResourceManager.GetString("EmptySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Date Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Existing Slot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExistingSlot {
            get {
                return ResourceManager.GetString("ExistingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Female に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go StoryCanvas HP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GoApplicationHP {
            get {
                return ResourceManager.GetString("GoApplicationHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you create new story? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCreateNewMessage {
            get {
                return ResourceManager.GetString("IsCreateNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you delete this slot? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsDeleteSlotMessage {
            get {
                return ResourceManager.GetString("IsDeleteSlotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you over-write this slot? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsOverwriteSlotMessage {
            get {
                return ResourceManager.GetString("IsOverwriteSlotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you quit this application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsQuitMessage {
            get {
                return ResourceManager.GetString("IsQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsWesternerName {
            get {
                return ResourceManager.GetString("IsWesternerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load from File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSetting_DateFormatType {
            get {
                return ResourceManager.GetString("LocationSetting_DateFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LocationSetting_IsWesternerName {
            get {
                return ResourceManager.GetString("LocationSetting_IsWesternerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Male に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network connection failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkConnectionFailed {
            get {
                return ResourceManager.GetString("NetworkConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusAbort {
            get {
                return ResourceManager.GetString("NetworkStatusAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusDeserializing {
            get {
                return ResourceManager.GetString("NetworkStatusDeserializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted for Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusErrorAndAbort {
            get {
                return ResourceManager.GetString("NetworkStatusErrorAndAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Making Tcp Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusMakingTcp {
            get {
                return ResourceManager.GetString("NetworkStatusMakingTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Making Udp Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusMakingUdp {
            get {
                return ResourceManager.GetString("NetworkStatusMakingUdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusNone {
            get {
                return ResourceManager.GetString("NetworkStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted for No Signals from Receivers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusNoSignalsAndAbort {
            get {
                return ResourceManager.GetString("NetworkStatusNoSignalsAndAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusReady {
            get {
                return ResourceManager.GetString("NetworkStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusReceived {
            get {
                return ResourceManager.GetString("NetworkStatusReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusReceiving {
            get {
                return ResourceManager.GetString("NetworkStatusReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receiving Meta Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusReceivingMetaData {
            get {
                return ResourceManager.GetString("NetworkStatusReceivingMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusSending {
            get {
                return ResourceManager.GetString("NetworkStatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending Meta Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusSendingMetaData {
            get {
                return ResourceManager.GetString("NetworkStatusSendingMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusSent {
            get {
                return ResourceManager.GetString("NetworkStatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready for Story Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusWaitingForData {
            get {
                return ResourceManager.GetString("NetworkStatusWaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready for Signal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkStatusWaitingForSignal {
            get {
                return ResourceManager.GetString("NetworkStatusWaitingForSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Trouble Shooting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkTroubleShooting {
            get {
                return ResourceManager.GetString("NetworkTroubleShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newest StoryCanvas Version:%Version% is avaliabled. Do you go to official page to download? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewestVersionAvaliabledMessage {
            get {
                return ResourceManager.GetString("NewestVersionAvaliabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewScene {
            get {
                return ResourceManager.GetString("NewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image pixel format is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoSupportedPixelFormatMessage {
            get {
                return ResourceManager.GetString("NoSupportedPixelFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed parameter column which value is empty in all entities. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParameterForAllEntityAppliedFalse {
            get {
                return ResourceManager.GetString("ParameterForAllEntityAppliedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added parameter column in all entities. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParameterForAllEntityAppliedTrue {
            get {
                return ResourceManager.GetString("ParameterForAllEntityAppliedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set all people に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParameterForAllPeople {
            get {
                return ResourceManager.GetString("ParameterForAllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Part に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Person に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Person に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintConfig {
            get {
                return ResourceManager.GetString("PrintConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Sub Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintSubTitle {
            get {
                return ResourceManager.GetString("PrintSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintTitle {
            get {
                return ResourceManager.GetString("PrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive by Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceiveNetwork {
            get {
                return ResourceManager.GetString("ReceiveNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Chapters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedChapters {
            get {
                return ResourceManager.GetString("RelatedChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedGroups {
            get {
                return ResourceManager.GetString("RelatedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related People に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedPeople {
            get {
                return ResourceManager.GetString("RelatedPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Places に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedPlaces {
            get {
                return ResourceManager.GetString("RelatedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Scenes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedScenes {
            get {
                return ResourceManager.GetString("RelatedScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related Words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelatedWords {
            get {
                return ResourceManager.GetString("RelatedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to File As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsFile {
            get {
                return ResourceManager.GetString("SaveAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data you&apos;re editing now is fared to be updated by other devices. Do you continue to save this data? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDataConflictMessage {
            get {
                return ResourceManager.GetString("SaveDataConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not save. Choose slot and save in Storage flyout. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFailedForNotChoosingSlot {
            get {
                return ResourceManager.GetString("SaveFailedForNotChoosingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFinishMessage {
            get {
                return ResourceManager.GetString("SaveFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene Designer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SceneDesigner {
            get {
                return ResourceManager.GetString("SceneDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SceneText {
            get {
                return ResourceManager.GetString("SceneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select any entity! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAnyEntityMessage {
            get {
                return ResourceManager.GetString("SelectAnyEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a chapter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectChapterMessage {
            get {
                return ResourceManager.GetString("SelectChapterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a group. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectGroupMessage {
            get {
                return ResourceManager.GetString("SelectGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectParameterMessage {
            get {
                return ResourceManager.GetString("SelectParameterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a person. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectPersonMessage {
            get {
                return ResourceManager.GetString("SelectPersonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a place. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectPlaceMessage {
            get {
                return ResourceManager.GetString("SelectPlaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a relation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectRelationMessage {
            get {
                return ResourceManager.GetString("SelectRelationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a scene. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectSceneMessage {
            get {
                return ResourceManager.GetString("SelectSceneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendFinishMessage {
            get {
                return ResourceManager.GetString("SendFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendNetwork {
            get {
                return ResourceManager.GetString("SendNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gender に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smart Phone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SmartPhone {
            get {
                return ResourceManager.GetString("SmartPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Date Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorageLocal {
            get {
                return ResourceManager.GetString("StorageLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storyline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Storyline {
            get {
                return ResourceManager.GetString("Storyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storyline Designer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorylineDesigner {
            get {
                return ResourceManager.GetString("StorylineDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Story Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StorySetting {
            get {
                return ResourceManager.GetString("StorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub Entity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubEntity {
            get {
                return ResourceManager.GetString("SubEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub Title Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubTitleFontSize {
            get {
                return ResourceManager.GetString("SubTitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub Title Margin Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubTitleMarginBottom {
            get {
                return ResourceManager.GetString("SubTitleMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Switching {
            get {
                return ResourceManager.GetString("Switching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Margin Botton に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextMarginBottom {
            get {
                return ResourceManager.GetString("TextMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Empty Title) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleFontSize {
            get {
                return ResourceManager.GetString("TitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title Margin Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleMarginBottom {
            get {
                return ResourceManager.GetString("TitleMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined error occured に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedErrorMessage {
            get {
                return ResourceManager.GetString("UndefinedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workspace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
